<?php 
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "assignment_module_6";

// Create a connection
$conn = mysqli_connect($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}

// Task 1: Retrieve customer information with the total number of orders
$task1_query = "
SELECT c.id AS customer_id, c.name, c.email, c.location, COUNT(orders.id) AS num_orders
FROM customers c
LEFT JOIN orders ON c.id = orders.customer_id
GROUP BY c.id
ORDER BY num_orders DESC;
";
$task1_result = $conn->query($task1_query);

// Task 2: Retrieve product name, quantity, and total amount for each order item
$task2_query = "
SELECT o.id AS order_id, p.name AS product_name, oi.quantity, oi.unit_price, oi.unit_price * oi.quantity AS total_amount
FROM orders o
INNER JOIN order_items oi ON o.id = oi.order_id
INNER JOIN products p ON oi.product_id = p.id
ORDER BY o.id ASC;
";
$task2_result = $conn->query($task2_query);

// Retrieve total revenue generated by each product category
$task3_query = "
SELECT c.name AS category_name, SUM(oi.unit_price * oi.quantity) AS total_revenue
FROM order_items oi
INNER JOIN products p ON oi.product_id = p.id
INNER JOIN categories c ON p.category_id = c.id
GROUP BY c.id
ORDER BY total_revenue DESC;
";
$task3_result = $conn->query($task3_query);

// Retrieve the top 5 customers with the highest total purchase amount
$task4_query = "
SELECT c.name, SUM(o.total_amount) AS total_purchase_amount
FROM customers c
INNER JOIN orders o ON c.id = o.customer_id
GROUP BY c.id
ORDER BY total_purchase_amount DESC
LIMIT 5;
";
$task4_result = $conn->query($task4_query);
?>
<!DOCTYPE html>
<html>

<head>
    <title>SQL Query Results</title>
    <!-- Include Bootstrap CSS styles -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
    <div class="container mt-4">
        <h2 class="text-danger mb-4">Task 1: Customer Information with Total Orders</h2>
        <table class="table table-striped table-bordered">
            <thead>
                <tr class="text-center">
                    <th>Customer ID</th>
                    <th>Customer Name</th>
                    <th>Customer Email</th>
                    <th>Customer Location</th>
                    <th>Total Orders</th>
                </tr>
            </thead>
            <tbody>
                <?php while ($row = $task1_result->fetch_assoc()) { ?>
                <tr class="text-center">
                    <td><?= $row['customer_id'] ?></td>
                    <td><?= $row['name'] ?></td>
                    <td><?= $row['email'] ?></td>
                    <td><?= $row['location'] ?></td>
                    <td><?= $row['num_orders'] ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <div class="container mt-4">
        <h2 class="text-danger mb-4">Task 2: Product Information for Order Items</h2>
        <table class="table table-striped table-bordered">
            <thead>
                <tr class="text-center">
                    <th>Order ID</th>
                    <th>Product Name</th>
                    <th>Quantity</th>
                    <th>Unit Price</th>
                    <th>Total Amount</th>
                </tr>
            </thead>
            <tbody>
                <?php while ($row = $task2_result->fetch_assoc()) { ?>
                <tr class="text-center">
                    <td><?= $row['order_id'] ?></td>
                    <td><?= $row['product_name'] ?></td>
                    <td><?= $row['quantity'] ?></td>
                    <td><?= $row['unit_price'] ?></td>
                    <td><?= $row['total_amount'] ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <div class="container mt-4">
        <h2 class="text-danger mb-4">Task 3: Total Revenue by Product Category</h2>
        <table class="table table-striped table-bordered">
            <thead>
                <tr class="text-center">
                    <th>Category Name</th>
                    <th>Total Revenue</th>
                </tr>
            </thead>
            <tbody>
                <?php while ($row = $task3_result->fetch_assoc()) { ?>
                <tr class="text-center">
                    <td><?= $row['category_name'] ?></td>
                    <td><?= $row['total_revenue'] ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
    <div class="container mt-4">
        <h2 class="text-danger mb-4">Task 4: Top 5 Customers by Total Purchase Amount</h2>
        <table class="table table-striped table-bordered">
            <thead>
                <tr class="text-center">
                    <th>Customer Name</th>
                    <th>Total Purchase Amount</th>
                </tr>
            </thead>
            <tbody>
                <?php while ($row = $task4_result->fetch_assoc()) { ?>
                <tr class="text-center">
                    <td><?= $row['name'] ?></td>
                    <td><?= $row['total_purchase_amount'] ?></td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</body>

</html>